# Project: Project2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"B:/Programs/DevC++/MinGW64/lib" -L"B:/Programs/DevC++/MinGW64/x86_64-w64-mingw32/lib" -L"B:/Programs/DevC++/DLLIncludes" -static-libgcc -mwindows -lopengl32
INCS     = -I"B:/Programs/DevC++/MinGW64/include" -I"B:/Programs/DevC++/MinGW64/x86_64-w64-mingw32/include" -I"B:/Programs/DevC++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"B:/Programs/DevC++/MinGW64/include" -I"B:/Programs/DevC++/MinGW64/x86_64-w64-mingw32/include" -I"B:/Programs/DevC++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"B:/Programs/DevC++/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"B:/Programs/DevC++/DLLIncludes"
BIN      = Project2.exe
CXXFLAGS = $(CXXINCS) -std=gnu99 -std=c++11
CFLAGS   = $(INCS) -std=gnu99 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
